### ISSUE TITLE
FlatItemBuff mod Compatibility

### ISSUE THREAD

**Issue by MeatMorning** [Moffein/RiskyMod#7] opened 2022-03-20 10:43 UTC
When both riskymod and Fflatitembuff mods are enabled, it causes an error and completely disables Riskymod. I've tested it out in new fresh profile with only riskymod and flatitembuff mods installed.
[LogOutput.log](https://github.com/Moffein/RiskyMod/files/8311052/LogOutput.log)

**Comment by gaforb** [comment] 2022-03-20 11:32
I believe specifically this is caused by the Titanic Knurl rework that FIB includes - Coincidentally, there's no config option to disable Knurl changes in RiskyMod.

**Comment by Moffein** [comment] 2022-03-20 23:24
Config option for disabling the Knurl changes has been merged and will ship in the next update. Generally, there's bound to be incompatibilities with other mods that modify Vanilla content, so the best option is to disable the corresponding setting in the RiskyMod Config when using other mods.

**Closed by Moffein** 2022-03-20 23:24 UTC
